export const DIGEST_CATEGORIES: { key: string; label: string; query: string }[] = [
  { key: 'iphone',     label: 'iPhones',          query: 'iPhone unlocked' },
  { key: 'macbook',    label: 'MacBooks',          query: 'MacBook Air' },
  { key: 'ipad',       label: 'iPads',             query: 'iPad unlocked' },
  { key: 'watch',      label: 'Apple Watch',       query: 'Apple Watch unlocked' },
  { key: 'airpods',    label: 'AirPods',           query: 'AirPods' },
  { key: 'nintendo',   label: 'Nintendo Switch',   query: 'Nintendo Switch' },
  { key: 'sneakers',   label: 'Sneakers',          query: 'Air Jordan sneakers' },
  { key: 'deadstock',  label: 'Deadstock Nikes',   query: 'Nike sneakers deadstock' },
  { key: 'pokemon',    label: 'Pokémon Cards',     query: 'Pokemon card PSA' },
  { key: 'sportcard',  label: 'Sports Cards',      query: 'sports card PSA graded' },
  { key: 'lego',       label: 'LEGO',              query: 'LEGO sealed' },
  { key: 'comic',      label: 'Comics',            query: 'vintage comic CGC' },
  { key: 'drone',      label: 'Drones',            query: 'DJI drone' },
  { key: 'camera',     label: 'Camera Lenses',     query: 'camera lens' },
  { key: 'gold',       label: 'Gold Coins',        query: 'gold coin' },
  { key: 'silver',     label: 'Silver Coins',      query: 'silver coin' },
  { key: 'games',      label: 'Video Games',       query: 'video game lot' },
  { key: 'keyboard',   label: 'Keyboards',         query: 'mechanical keyboard' },
  { key: 'sunglasses', label: 'Sunglasses',        query: 'designer sunglasses' },
  { key: 'luxwatch',   label: 'Luxury Watches',    query: 'luxury watch' },
];
