export const DIGEST_CATEGORIES: { key: string; label: string; query: string }[] = [
  { key: 'iphone',     label: 'iPhones',          query: 'iPhone 15 16 unlocked refurbished' },
  { key: 'macbook',    label: 'MacBooks',          query: 'MacBook Air M2 M3 refurbished' },
  { key: 'ipad',       label: 'iPads',             query: 'iPad Air iPad Pro 2022 2023 2024 unlocked' },
  { key: 'watch',      label: 'Apple Watch',       query: 'Apple Watch Series 9 10 Ultra unlocked' },
  { key: 'airpods',    label: 'AirPods',           query: 'AirPods Pro 2nd 3rd generation' },
  { key: 'nintendo',   label: 'Nintendo Switch',   query: 'Nintendo Switch OLED' },
  { key: 'sneakers',   label: 'Sneakers',          query: 'Air Jordan sneakers deadstock' },
  { key: 'deadstock',  label: 'Deadstock Nikes',   query: 'Nike Dunk sneakers deadstock new' },
  { key: 'pokemon',    label: 'Pokémon Cards',     query: 'Pokemon card PSA 10' },
  { key: 'sportcard',  label: 'Sports Cards',      query: 'sports card PSA 10 graded rookie' },
  { key: 'lego',       label: 'LEGO',              query: 'LEGO sealed retired' },
  { key: 'comic',      label: 'Comics',            query: 'comic CGC 9.8 key issue' },
  { key: 'drone',      label: 'Drones',            query: 'DJI Mini 4 Air 3 drone' },
  { key: 'camera',     label: 'Camera Lenses',     query: 'Sony Canon Nikon lens L mount' },
  { key: 'gold',       label: 'Gold Coins',        query: 'gold coin 1oz American Eagle' },
  { key: 'silver',     label: 'Silver Coins',      query: 'silver coin 1oz American Eagle' },
  { key: 'games',      label: 'Video Games',       query: 'PS5 Xbox Series X game sealed' },
  { key: 'keyboard',   label: 'Keyboards',         query: 'mechanical keyboard custom keycaps' },
  { key: 'sunglasses', label: 'Sunglasses',        query: 'Louis Vuitton Gucci sunglasses authentic' },
  { key: 'luxwatch',   label: 'Luxury Watches',    query: 'Rolex Omega luxury watch' },
];
