export const DIGEST_CATEGORIES: { key: string; label: string; query: string }[] = [
  { key: 'iphone',     label: 'iPhones',          query: 'iPhone unlocked refurbished' },
  { key: 'macbook',    label: 'MacBooks',          query: 'MacBook Air refurbished' },
  { key: 'ipad',       label: 'iPads',             query: 'iPad unlocked refurbished' },
  { key: 'watch',      label: 'Apple Watch',       query: 'Apple Watch unlocked' },
  { key: 'airpods',    label: 'AirPods',           query: 'AirPods Pro' },
  { key: 'nintendo',   label: 'Nintendo Switch',   query: 'Nintendo Switch OLED' },
  { key: 'sneakers',   label: 'Sneakers',          query: 'Air Jordan sneakers new' },
  { key: 'deadstock',  label: 'Deadstock Nikes',   query: 'Nike Dunk deadstock new' },
  { key: 'pokemon',    label: 'Pokémon Cards',     query: 'Pokemon card PSA 10' },
  { key: 'sportcard',  label: 'Sports Cards',      query: 'sports card PSA 10 graded' },
  { key: 'lego',       label: 'LEGO',              query: 'LEGO sealed set' },
  { key: 'comic',      label: 'Comics',            query: 'comic CGC graded' },
  { key: 'drone',      label: 'Drones',            query: 'DJI drone' },
  { key: 'camera',     label: 'Camera Lenses',     query: 'camera lens Sony Canon' },
  { key: 'gold',       label: 'Gold Coins',        query: 'gold coin bullion' },
  { key: 'silver',     label: 'Silver Coins',      query: 'silver coin bullion' },
  { key: 'games',      label: 'Video Games',       query: 'PS5 Xbox Series X game' },
  { key: 'keyboard',   label: 'Keyboards',         query: 'mechanical keyboard' },
  { key: 'sunglasses', label: 'Sunglasses',        query: 'designer sunglasses luxury' },
  { key: 'luxwatch',   label: 'Luxury Watches',    query: 'Rolex Omega watch' },
];
