import { EbayItem } from './ebay';

// Realistic mock deals for electronics and collectibles - used when EBAY_MOCK=true
export const MOCK_DEALS: EbayItem[] = [
  // ── Electronics ──────────────────────────────────────────────────────
  {
    itemId: 'mock-001',
    title: 'Apple MacBook Air M2 13" 8GB 256GB Space Gray - Near Mint',
    price: 299,
    currency: 'USD',
    marketPrice: 1099,
    discountPct: 73,
    condition: 'Like New',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=MacBook+Air',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-001',
    seller: 'techflip_pro',
    sellerFeedbackScore: 2847,
    sellerFeedbackPercent: 99.8,
    location: 'Austin, TX',
    category: 'Laptops & Netbooks',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-002',
    title: 'Sony PlayStation 5 Disc Edition Console - Complete in Box',
    price: 149,
    currency: 'USD',
    marketPrice: 499,
    discountPct: 70,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=PS5',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-002',
    seller: 'game_vault_usa',
    sellerFeedbackScore: 412,
    sellerFeedbackPercent: 97.1,
    location: 'Chicago, IL',
    category: 'Video Game Consoles',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-003',
    title: 'Apple iPhone 14 Pro 256GB Deep Purple - Unlocked, Excellent',
    price: 189,
    currency: 'USD',
    marketPrice: 799,
    discountPct: 76,
    condition: 'Like New',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=iPhone+14+Pro',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-003',
    seller: 'wireless_depot',
    sellerFeedbackScore: 5621,
    sellerFeedbackPercent: 99.6,
    location: 'Miami, FL',
    category: 'Cell Phones & Smartphones',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-004',
    title: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones - Black',
    price: 69,
    currency: 'USD',
    marketPrice: 349,
    discountPct: 80,
    condition: 'Very Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=Sony+XM5',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-004',
    seller: 'audiogear_resale',
    sellerFeedbackScore: 1203,
    sellerFeedbackPercent: 99.2,
    location: 'Seattle, WA',
    category: 'Headphones',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-005',
    title: 'DJI Mini 3 Pro Drone + RC Controller - Barely Used, All Accessories',
    price: 129,
    currency: 'USD',
    marketPrice: 759,
    discountPct: 83,
    condition: 'Like New',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=DJI+Mini+3',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-005',
    seller: 'sky_deals_usa',
    sellerFeedbackScore: 18,
    sellerFeedbackPercent: 94.4,
    location: 'Denver, CO',
    category: 'Camera Drones',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-006',
    title: 'Apple iPad Air 5th Gen 256GB Wi-Fi Space Gray',
    price: 149,
    currency: 'USD',
    marketPrice: 749,
    discountPct: 80,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=iPad+Air',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-006',
    seller: 'apple_outlet99',
    sellerFeedbackScore: 3341,
    sellerFeedbackPercent: 99.4,
    location: 'Portland, OR',
    category: 'Tablets & eBook Readers',
    shippingCost: 5.99,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-007',
    title: 'Samsung 65" QLED 4K Smart TV QN65Q80C - 2023, Perfect Panel',
    price: 349,
    currency: 'USD',
    marketPrice: 1299,
    discountPct: 73,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=Samsung+65%22',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-007',
    seller: 'tv_liquidators',
    sellerFeedbackScore: 891,
    sellerFeedbackPercent: 98.7,
    location: 'Dallas, TX',
    category: 'Televisions',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-008',
    title: 'GoPro HERO 11 Black Action Camera - Complete Kit, 2 Batteries',
    price: 79,
    currency: 'USD',
    marketPrice: 399,
    discountPct: 80,
    condition: 'Very Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=GoPro+11',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-008',
    seller: 'action_cam_hub',
    sellerFeedbackScore: 674,
    sellerFeedbackPercent: 99.1,
    location: 'Nashville, TN',
    category: 'Action Cameras',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-009',
    title: 'Nintendo Switch OLED Model - White, All Original Accessories',
    price: 89,
    currency: 'USD',
    marketPrice: 349,
    discountPct: 74,
    condition: 'Like New',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=Switch+OLED',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-009',
    seller: 'nintendoflip',
    sellerFeedbackScore: 156,
    sellerFeedbackPercent: 99.4,
    location: 'Phoenix, AZ',
    category: 'Video Game Consoles',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-010',
    title: 'Apple Watch Ultra 2 49mm Titanium - GPS + Cellular, Excellent',
    price: 299,
    currency: 'USD',
    marketPrice: 799,
    discountPct: 76,
    condition: 'Like New',
    imageUrl: 'https://placehold.co/300x300/1e293b/60a5fa?text=Watch+Ultra',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-010',
    seller: 'wearable_depot',
    sellerFeedbackScore: 2109,
    sellerFeedbackPercent: 99.7,
    location: 'Boston, MA',
    category: 'Smart Watches',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },

  // ── Collectibles ──────────────────────────────────────────────────────
  {
    itemId: 'mock-011',
    title: 'Pokemon Base Set Charizard Holo 1st Edition PSA 7 - BGS Verified',
    price: 799,
    currency: 'USD',
    marketPrice: 3200,
    discountPct: 75,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Charizard+PSA7',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-011',
    seller: 'poke_vault_graded',
    sellerFeedbackScore: 4892,
    sellerFeedbackPercent: 99.9,
    location: 'Los Angeles, CA',
    category: 'Pokemon Trading Card Games',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-012',
    title: 'Michael Jordan 1986 Fleer Rookie #57 PSA 8 - Centered, Sharp Corners',
    price: 249,
    currency: 'USD',
    marketPrice: 1100,
    discountPct: 77,
    condition: 'Very Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Jordan+Rookie',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-012',
    seller: 'card_king_chicago',
    sellerFeedbackScore: 3201,
    sellerFeedbackPercent: 99.5,
    location: 'Chicago, IL',
    category: 'Basketball Cards',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-013',
    title: 'LEGO Star Wars UCS Millennium Falcon 75192 - SEALED, New in Box',
    price: 499,
    currency: 'USD',
    marketPrice: 1799,
    discountPct: 72,
    condition: 'New',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=LEGO+Falcon',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-013',
    seller: 'brick_investments',
    sellerFeedbackScore: 788,
    sellerFeedbackPercent: 99.8,
    location: 'Atlanta, GA',
    category: 'LEGO Complete Sets',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-014',
    title: 'Tom Brady 2000 Contenders Rookie Ticket Auto PSA 9 - Population 12',
    price: 349,
    currency: 'USD',
    marketPrice: 1500,
    discountPct: 77,
    condition: 'Very Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Brady+Auto',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-014',
    seller: 'gridiron_grails',
    sellerFeedbackScore: 1547,
    sellerFeedbackPercent: 99.3,
    location: 'New England, MA',
    category: 'Football Cards',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-015',
    title: 'Star Wars Original Trilogy 1977 Lobby Card Set (8) - Near Mint',
    price: 129,
    currency: 'USD',
    marketPrice: 599,
    discountPct: 78,
    condition: 'Very Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Star+Wars+Lobby',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-015',
    seller: 'cinema_relics',
    sellerFeedbackScore: 42,
    sellerFeedbackPercent: 95.2,
    location: 'Hollywood, CA',
    category: 'Movie Memorabilia',
    shippingCost: 8.99,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-016',
    title: 'Pokemon Base Set Booster Box SEALED Unlimited - WOTC 1999',
    price: 899,
    currency: 'USD',
    marketPrice: 3500,
    discountPct: 74,
    condition: 'New',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Poke+Booster',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-016',
    seller: 'sealed_wax_world',
    sellerFeedbackScore: 2233,
    sellerFeedbackPercent: 99.7,
    location: 'San Francisco, CA',
    category: 'Pokemon Trading Card Games',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-017',
    title: 'Vintage Apple Macintosh 128K - Working, Original Box & Manuals',
    price: 299,
    currency: 'USD',
    marketPrice: 1200,
    discountPct: 75,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Mac+128K',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-017',
    seller: 'vintage_byte',
    sellerFeedbackScore: 309,
    sellerFeedbackPercent: 98.4,
    location: 'Cupertino, CA',
    category: 'Vintage Computers',
    shippingCost: 24.99,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-018',
    title: 'LeBron James 2003 Topps Chrome Rookie Refractor #111 PSA 9',
    price: 199,
    currency: 'USD',
    marketPrice: 899,
    discountPct: 78,
    condition: 'Very Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=LeBron+RC',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-018',
    seller: 'hoops_royalty',
    sellerFeedbackScore: 1876,
    sellerFeedbackPercent: 99.6,
    location: 'Cleveland, OH',
    category: 'Basketball Cards',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-019',
    title: 'Rolex Submariner Hulk 116610LV Box & Papers 2019 - Serviced',
    price: 8999,
    currency: 'USD',
    marketPrice: 18500,
    discountPct: 51,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Rolex+Hulk',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-019',
    seller: 'luxury_timepieces',
    sellerFeedbackScore: 623,
    sellerFeedbackPercent: 99.1,
    location: 'New York, NY',
    category: 'Wristwatches',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
  {
    itemId: 'mock-020',
    title: 'Batman #1 (1940) CGC 3.0 - Golden Age, First Joker Cover',
    price: 1499,
    currency: 'USD',
    marketPrice: 6000,
    discountPct: 75,
    condition: 'Good',
    imageUrl: 'https://placehold.co/300x300/1e293b/f97316?text=Batman+%231+CGC',
    additionalImages: [],
    itemUrl: 'https://www.ebay.com/itm/mock-020',
    seller: 'golden_age_comics',
    sellerFeedbackScore: 1102,
    sellerFeedbackPercent: 99.4,
    location: 'New York, NY',
    category: 'Golden Age Comics',
    shippingCost: 0,
    listingType: 'FIXED_PRICE',
    localPickupOnly: false,
    listingDate: null,
    quantity: null,
  },
];
